version: "3.1"
services:
  db:
    image: mysql
    command: --mysql-native-password=ON
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "$(Password)"
      MYSQL_DATABASE: "hexDB"
    ports:
      - "3307:3306"
    volumes:
      - ./db/hexDB:/docker-entrypoint-initdb.d
  
  grpc:
    build: .
    container_name: grpc
    restart: always
    ports:
      - "50051:50051"
    depends_on:
      - db
    command: ["go", "test", "-v", "./..."]
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=$(Password)
      - MYSQL_DB=hexDB
      - DB_DRIVER=mysql
      - DB_SOURCE=root:$(Password)@tcp(db:3306)/hexDB?charset=utf8mb4&parseTime=True&loc=Local